#!/bin/bash

set -o nounset
set -o errexit

echo "${INIT_PWD}"
echo "${INIT_USER}"
echo "${DB_NAME}"

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE ROLE writers;
    CREATE ROLE readers;
    CREATE ROLE humans;
    CREATE ROLE sudoers;
    CREATE ROLE c3;
EOSQL


psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER "${INIT_USER}" WITH ENCRYPTED PASSWORD '${INIT_PWD}' IN ROLE writers;
    ALTER USER "${INIT_USER}" WITH SUPERUSER;
EOSQL


psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE DATABASE "${DB_NAME}" OWNER writers;
    \c "${DB_NAME}"
    ALTER SCHEMA "public" OWNER TO writers;
    CREATE EXTENSION IF NOT EXISTS intarray;
EOSQL


psql -v ON_ERROR_STOP=1 --username="${INIT_USER}" --dbname="${DB_NAME}" <<-EOSQL
    -- Schema level grants
    GRANT ALL ON SCHEMA public TO writers;
    GRANT USAGE ON SCHEMA public TO writers;
    GRANT USAGE ON SCHEMA public TO readers;
    GRANT ALL ON SCHEMA public TO c3;
    
    -- Database-wide default privileges
    ALTER DEFAULT PRIVILEGES
    GRANT ALL ON TABLES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT ALL ON SEQUENCES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT ALL ON FUNCTIONS TO sudoers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT ALL ON TYPES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO writers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO writers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO writers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO writers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT SELECT ON TABLES TO readers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT USAGE, SELECT ON SEQUENCES TO readers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO readers;
    
    ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO readers;
EOSQL


psql -v ON_ERROR_STOP=1 --username="${INIT_USER}" --dbname="${DB_NAME}" <<-EOSQL
    -- Schema-specific default privileges (these are mostly redundant but kept for clarity)
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT ALL ON TABLES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT ALL ON FUNCTIONS TO sudoers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT ALL ON TYPES TO sudoers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO writers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO writers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT EXECUTE ON FUNCTIONS TO writers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE ON TYPES TO writers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT ON TABLES TO readers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO readers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT EXECUTE ON FUNCTIONS TO readers;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE ON TYPES TO readers;
EOSQL